Add database
AndreySanzharov/java-filmorate pull request #5
Opened 2024-11-02 11:41 UTC by AndreySanzharov

2024-11-05 20:13 UTC, sergeymamonov requested changes

2024-11-05 20:13 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/GenreRepository.java
> +            update(BACTCH_QUERY, filmId, genreId);
Не нужно делать запросы к базе в цикле. В данном случае можно сделать INSERT INTO VALUES и вставить все значения за один запрос.

2024-11-05 20:13 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Collection<Film> findAll();
Лучше использовать более узкий интерфейс, лист или множество.

2024-11-05 20:13 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    MPA_NAME VARCHAR NOT NULL
Не забывайте ограничивать размер varchar.

2024-11-06 12:39 UTC, AndreySanzharov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        film.setGenres(getGenresByFilm(id));
Так запрос кажется проще для составоения и читаемее

2024-11-06 19:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +import ru.yandex.practicum.filmorate.model.*;
Сделайте поиск по проекты Command+Shift+F, укажите, например .*; и увидите, где еще есть импорт через звездочку.

2024-11-06 19:46 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +    private static final String FOR_ALL_FILMS_QUERY = "SELECT * FROM FILMS f, " +
Сделайте поиск по проекту SELECT *
В запросе нужно доставать только то, что нужно и не делать нагрузку на БД доставая неиспользуемые поля.

2024-11-06 19:51 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        film.setGenres(getGenresByFilm(id));
Так вы делаете два запроса. То есть метод отрабатывает дольше. Нагрузка на базу и сеть выше.

2024-11-06 20:00 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +        return rowDeleted > 0;
Если так делать, то метод delete не будет идемпотентным. Если еще не знакомы с этим термином, то лучше почитать.

2024-11-06 20:00 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/GenreRepository.java
> +            update(BACTCH_QUERY, filmId, genreId);
Здесь нужно в один запрос набрать все значения и выполнить этот запрос.

2024-11-06 20:01 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    MPA_NAME VARCHAR NOT NULL
Проверьте еще раз.

2024-11-06 20:03 UTC, sergeymamonov approved these changes

2024-11-06 20:03 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
Общепринято называть идентификатор id. Аналогично для остальных таблиц.

2024-11-19 12:11 UTC, AndreySanzharov commented on src/main/resources/schema.sql
> +    USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
Решил специально разделить, местами казалось удобнее писать запросы. Особенно сейчас будет неудобно менять все обратно с учетом того, что inteliji не покажет использованные названия в коде. Вроде это не особо критичный недочет.

2024-11-19 12:38 UTC, merged